// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Symulator_Nozownika.Data;

#nullable disable

namespace Symulator_Nozownika.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607220849_FixUserReportDeleteBehavior")]
    partial class FixUserReportDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Symulator_Nozownika.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zdobądź łącznie 2000 punktów.",
                            ImagePath = "/images/achiv/2000.png",
                            Name = "Nowicjusz",
                            TargetValue = 2000,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zdobądź łącznie 5000 punktów.",
                            ImagePath = "/images/achiv/5000.png",
                            Name = "Doświadczony",
                            TargetValue = 5000,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zdobądź łącznie 10000 punktów.",
                            ImagePath = "/images/achiv/10000.png",
                            Name = "Weteran",
                            TargetValue = 10000,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zagraj w swoją pierwszą grę.",
                            ImagePath = "/images/achiv/first-game.png",
                            Name = "Pierwsza krew",
                            TargetValue = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kliknij 100 razy w trakcie jednej gry.",
                            ImagePath = "/images/achiv/100-clicks-in-one-game.png",
                            Name = "Szybkie palce",
                            TargetValue = 100,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zdobądź łącznie 300 kliknięć we wszystkich grach.",
                            ImagePath = "/images/achiv/300-clicks.png",
                            Name = "Klikacz",
                            TargetValue = 300,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Zdobądź łącznie 500 kliknięć we wszystkich grach.",
                            ImagePath = "/images/achiv/500-clicks.png",
                            Name = "Wprawiony Klikacz",
                            TargetValue = 500,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Zdobądź łącznie 1000 kliknięć we wszystkich grach.",
                            ImagePath = "/images/achiv/1000-clicks.png",
                            Name = "Maniak",
                            TargetValue = 1000,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Zdobądź łącznie 3000 kliknięć we wszystkich grach.",
                            ImagePath = "/images/achiv/3000-clicks.png",
                            Name = "3000 GWIAZD!",
                            TargetValue = 3000,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.ClubMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.ClubMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMessages");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.CoinWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CoinWallets");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Balance = 9999,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9999
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.DemoLockout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DemoLockouts");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("FavoriteWeapons");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevelThreshold")
                        .HasColumnType("int");

                    b.Property<int>("NextLevelThreshold")
                        .HasColumnType("int");

                    b.Property<int>("TotalScoreSnapshot")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            CurrentLevel = 10,
                            CurrentLevelThreshold = 5040,
                            NextLevelThreshold = 6000,
                            TotalScoreSnapshot = 5500,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 9999
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.MessageReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReportedMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReportedMessageId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("MessageReports");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Potion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("EffectStrength")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Potions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Krótki zastrzyk energii do szybszej rozgrywki.",
                            DurationInSeconds = 30,
                            EffectStrength = 10,
                            ImageUrl = "/images/scissors.png",
                            Name = "Mała potka energii",
                            Price = 120
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mocniejsze uderzenia przez chwilę.",
                            DurationInSeconds = 45,
                            EffectStrength = 20,
                            ImageUrl = "/images/dagger.png",
                            Name = "Potka furii",
                            Price = 260
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pomaga utrzymać rytm i serię kliknięć.",
                            DurationInSeconds = 60,
                            EffectStrength = 30,
                            ImageUrl = "/images/katana.png",
                            Name = "Eliksir skupienia",
                            Price = 400
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedPotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PotionId")
                        .HasColumnType("int");

                    b.Property<int>("PricePaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotionId");

                    b.HasIndex("UserId", "PotionId")
                        .IsUnique();

                    b.ToTable("PurchasedPotions");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PricePaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.HasIndex("UserId", "WeaponId")
                        .IsUnique();

                    b.ToTable("PurchasedWeapons");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedWeaponUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PricePaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponUpgradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeaponUpgradeId");

                    b.HasIndex("UserId", "WeaponUpgradeId")
                        .IsUnique();

                    b.ToTable("PurchasedWeaponUpgrades");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuestType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResetsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardCoins")
                        .HasColumnType("int");

                    b.Property<int>("RewardXp")
                        .HasColumnType("int");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kliknij 50 razy w trakcie dzisiejszej sesji.",
                            Name = "Nożownik Dnia",
                            QuestType = 0,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 10,
                            RewardXp = 25,
                            TargetValue = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kliknij 150 razy w trakcie dzisiejszej sesji.",
                            Name = "Szybkie Paluszki",
                            QuestType = 0,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 25,
                            RewardXp = 60,
                            TargetValue = 150
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kliknij 300 razy w trakcie dzisiejszej sesji.",
                            Name = "British Special",
                            QuestType = 0,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 50,
                            RewardXp = 120,
                            TargetValue = 300
                        },
                        new
                        {
                            Id = 4,
                            Description = "Zdobądź 500 punktów w ciągu dnia.",
                            Name = "Nożyce Jak Brzytwa",
                            QuestType = 1,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 15,
                            RewardXp = 40,
                            TargetValue = 500
                        },
                        new
                        {
                            Id = 5,
                            Description = "Zdobądź 1500 punktów w ciągu dnia.",
                            Name = "Daj mu jeszcze jeden w serce!",
                            QuestType = 1,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 35,
                            RewardXp = 90,
                            TargetValue = 1500
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zdobądź 3000 punktów w ciągu dnia.",
                            Name = "Prawdziwy Londyńczyk",
                            QuestType = 1,
                            ResetsAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RewardCoins = 75,
                            RewardXp = 200,
                            TargetValue = 3000
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.SavedScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedScores");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemoGamesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SelectedWeaponId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Country = "Poland",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DemoGamesPlayed = 0,
                            Email = "debug@example.local",
                            FirstName = "Debug",
                            IsDemo = false,
                            LastName = "Account",
                            Password = "debugdebug1",
                            Role = 0,
                            UserName = "debug"
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserAccountId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserPenalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RelatedReportId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RelatedReportId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPenalties");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserQuestProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRewardClaimed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ProgressDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId", "QuestId")
                        .IsUnique();

                    b.ToTable("UserQuestProgresses");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("UserReports");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("HighestScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalPlayTime")
                        .HasColumnType("time");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatistics");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            CurrentStreak = 0,
                            HighestScore = 0,
                            LastPlayedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LongestStreak = 0,
                            TotalClicks = 0,
                            TotalGamesPlayed = 0,
                            TotalPlayTime = new TimeSpan(0, 0, 0, 0, 0),
                            TotalScore = 5500,
                            UserId = 9999
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cooldown")
                        .HasColumnType("float");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cooldown = 0.40000000000000002,
                            Damage = 10,
                            ImageUrl = "/images/knife.png",
                            Name = "Kitchen Knife"
                        },
                        new
                        {
                            Id = 2,
                            Cooldown = 0.59999999999999998,
                            Damage = 25,
                            ImageUrl = "/images/dagger.png",
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 3,
                            Cooldown = 0.90000000000000002,
                            Damage = 45,
                            ImageUrl = "/images/machete.png",
                            Name = "Machete"
                        },
                        new
                        {
                            Id = 4,
                            Cooldown = 1.1000000000000001,
                            Damage = 55,
                            ImageUrl = "/images/sword.png",
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 5,
                            Cooldown = 1.5,
                            Damage = 70,
                            ImageUrl = "/images/axe.png",
                            Name = "Axe"
                        },
                        new
                        {
                            Id = 6,
                            Cooldown = 0.69999999999999996,
                            Damage = 40,
                            ImageUrl = "/images/spear.png",
                            Name = "Spear"
                        },
                        new
                        {
                            Id = 7,
                            Cooldown = 1.3,
                            Damage = 60,
                            ImageUrl = "/images/cleaver.png",
                            Name = "Cleaver"
                        },
                        new
                        {
                            Id = 8,
                            Cooldown = 2.0,
                            Damage = 90,
                            ImageUrl = "/images/mace.png",
                            Name = "Mace"
                        },
                        new
                        {
                            Id = 9,
                            Cooldown = 0.5,
                            Damage = 50,
                            ImageUrl = "/images/katana.png",
                            Name = "Katana"
                        },
                        new
                        {
                            Id = 10,
                            Cooldown = 0.10000000000000001,
                            Damage = 2,
                            ImageUrl = "/images/scissors.png",
                            Name = "Scissors"
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.WeaponUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CooldownReduction")
                        .HasColumnType("float");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponUpgrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CooldownReduction = 0.02,
                            DamageBonus = 4,
                            Description = "Lepsza krawędź zwiększa obrażenia kuchennego noża.",
                            ImageUrl = "/images/knife.png",
                            Name = "Ostrzenie Kitchen Knife",
                            Price = 300,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 2,
                            CooldownReduction = 0.050000000000000003,
                            DamageBonus = 6,
                            Description = "Lepszy balans skraca czas odnowienia sztyletu.",
                            ImageUrl = "/images/dagger.png",
                            Name = "Wyważenie Dagger",
                            Price = 650,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 3,
                            CooldownReduction = 0.080000000000000002,
                            DamageBonus = 12,
                            Description = "Wzmocnione ostrze zapewnia dodatkową moc katanie.",
                            ImageUrl = "/images/katana.png",
                            Name = "Hartowana Katana",
                            Price = 1800,
                            WeaponId = 9
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Club", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.ClubMember", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.ClubMessage", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Club", "Club")
                        .WithMany("Messages")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.CoinWallet", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithOne("CoinWallet")
                        .HasForeignKey("Symulator_Nozownika.Models.CoinWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Level", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithOne("Level")
                        .HasForeignKey("Symulator_Nozownika.Models.Level", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.MessageReport", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.ClubMessage", "ReportedMessage")
                        .WithMany()
                        .HasForeignKey("ReportedMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReportedMessage");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedPotion", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Potion", "Potion")
                        .WithMany()
                        .HasForeignKey("PotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany("PurchasedPotions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Potion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedWeapon", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany("PurchasedWeapons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.PurchasedWeaponUpgrade", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany("PurchasedWeaponUpgrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.WeaponUpgrade", "WeaponUpgrade")
                        .WithMany()
                        .HasForeignKey("WeaponUpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WeaponUpgrade");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.SavedScore", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "SelectedWeapon")
                        .WithMany()
                        .HasForeignKey("SelectedWeaponId");

                    b.Navigation("Club");

                    b.Navigation("SelectedWeapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAchievement", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserPenalty", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserReport", "RelatedReport")
                        .WithMany()
                        .HasForeignKey("RelatedReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("RelatedReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserQuestProgress", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserReport", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserStatistics", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("Symulator_Nozownika.Models.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.WeaponUpgrade", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Club", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.Navigation("CoinWallet");

                    b.Navigation("Level");

                    b.Navigation("PurchasedPotions");

                    b.Navigation("PurchasedWeaponUpgrades");

                    b.Navigation("PurchasedWeapons");

                    b.Navigation("Statistics");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
