// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Symulator_Nozownika.Data;

#nullable disable

namespace Symulator_Nozownika.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515100000_FixClubsAndAddClubMembers")]
    partial class FixClubsAndAddClubMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial migration file - just for the ClubMembers table
#pragma warning restore 612, 618
        }
    }
}
