// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Symulator_Nozownika.Migrations
{
    [DbContext(typeof(Symulator_Nozownika.Data.AppDbContext))]
    [Migration("20260403100000_AddClubsFeature")]
    partial class AddClubsFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Symulator_Nozownika.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("FavoriteWeapons");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelectedWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("SelectedWeaponId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cooldown")
                        .HasColumnType("float");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cooldown = 0.40000000000000002,
                            Damage = 10,
                            ImageUrl = "/images/knife.png",
                            Name = "Kitchen Knife"
                        },
                        new
                        {
                            Id = 2,
                            Cooldown = 0.59999999999999998,
                            Damage = 25,
                            ImageUrl = "/images/dagger.png",
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 3,
                            Cooldown = 0.90000000000000002,
                            Damage = 45,
                            ImageUrl = "/images/machete.png",
                            Name = "Machete"
                        },
                        new
                        {
                            Id = 4,
                            Cooldown = 1.1000000000000001,
                            Damage = 55,
                            ImageUrl = "/images/sword.png",
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 5,
                            Cooldown = 1.5,
                            Damage = 70,
                            ImageUrl = "/images/axe.png",
                            Name = "Axe"
                        },
                        new
                        {
                            Id = 6,
                            Cooldown = 0.69999999999999996,
                            Damage = 40,
                            ImageUrl = "/images/spear.png",
                            Name = "Spear"
                        },
                        new
                        {
                            Id = 7,
                            Cooldown = 1.3,
                            Damage = 60,
                            ImageUrl = "/images/cleaver.png",
                            Name = "Cleaver"
                        },
                        new
                        {
                            Id = 8,
                            Cooldown = 2.0,
                            Damage = 90,
                            ImageUrl = "/images/mace.png",
                            Name = "Mace"
                        },
                        new
                        {
                            Id = 9,
                            Cooldown = 0.5,
                            Damage = 50,
                            ImageUrl = "/images/katana.png",
                            Name = "Katana"
                        },
                        new
                        {
                            Id = 10,
                            Cooldown = 0.10000000000000001,
                            Damage = 2,
                            ImageUrl = "/images/scissors.png",
                            Name = "Scissors"
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "SelectedWeapon")
                        .WithMany()
                        .HasForeignKey("SelectedWeaponId");

                    b.Navigation("Club");

                    b.Navigation("SelectedWeapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Club", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
