// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Symulator_Nozownika.Data;

#nullable disable

namespace Symulator_Nozownika.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425140415_AddAchievementsSystem")]
    partial class AddAchievementsSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Symulator_Nozownika.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zdobądź łącznie 2000 punktów.",
                            ImagePath = "/images/achiv/2000.png",
                            Name = "Nowicjusz",
                            TargetValue = 2000,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zdobądź łącznie 5000 punktów.",
                            ImagePath = "/images/achiv/5000.png",
                            Name = "Doświadczony",
                            TargetValue = 5000,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zdobądź łącznie 10000 punktów.",
                            ImagePath = "/images/achiv/10000.png",
                            Name = "Weteran",
                            TargetValue = 10000,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("FavoriteWeapons");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.SavedScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedScores");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelectedWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelectedWeaponId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserAccountId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("HighestScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TotalPlayTime")
                        .HasColumnType("time");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cooldown")
                        .HasColumnType("float");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cooldown = 0.40000000000000002,
                            Damage = 10,
                            ImageUrl = "/images/knife.png",
                            Name = "Kitchen Knife"
                        },
                        new
                        {
                            Id = 2,
                            Cooldown = 0.59999999999999998,
                            Damage = 25,
                            ImageUrl = "/images/dagger.png",
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 3,
                            Cooldown = 0.90000000000000002,
                            Damage = 45,
                            ImageUrl = "/images/machete.png",
                            Name = "Machete"
                        },
                        new
                        {
                            Id = 4,
                            Cooldown = 1.1000000000000001,
                            Damage = 55,
                            ImageUrl = "/images/sword.png",
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 5,
                            Cooldown = 1.5,
                            Damage = 70,
                            ImageUrl = "/images/axe.png",
                            Name = "Axe"
                        },
                        new
                        {
                            Id = 6,
                            Cooldown = 0.69999999999999996,
                            Damage = 40,
                            ImageUrl = "/images/spear.png",
                            Name = "Spear"
                        },
                        new
                        {
                            Id = 7,
                            Cooldown = 1.3,
                            Damage = 60,
                            ImageUrl = "/images/cleaver.png",
                            Name = "Cleaver"
                        },
                        new
                        {
                            Id = 8,
                            Cooldown = 2.0,
                            Damage = 90,
                            ImageUrl = "/images/mace.png",
                            Name = "Mace"
                        },
                        new
                        {
                            Id = 9,
                            Cooldown = 0.5,
                            Damage = 50,
                            ImageUrl = "/images/katana.png",
                            Name = "Katana"
                        },
                        new
                        {
                            Id = 10,
                            Cooldown = 0.10000000000000001,
                            Damage = 2,
                            ImageUrl = "/images/scissors.png",
                            Name = "Scissors"
                        });
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.FavoriteWeapon", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.HighScore", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.SavedScore", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Weapon", "SelectedWeapon")
                        .WithMany()
                        .HasForeignKey("SelectedWeaponId");

                    b.Navigation("SelectedWeapon");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAchievement", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserStatistics", b =>
                {
                    b.HasOne("Symulator_Nozownika.Models.UserAccount", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("Symulator_Nozownika.Models.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Symulator_Nozownika.Models.UserAccount", b =>
                {
                    b.Navigation("Statistics");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
